workflows:
  ios-unsigned:
    name: Build unsigned iOS IPA (.NET MAUI)
    max_build_duration: 60
    environment:
      xcode: latest
    scripts:
      - name: Install .NET 9 SDK via Homebrew
        script: |
          brew update
          brew install dotnet@9
          export DOTNET_ROOT=/opt/homebrew/opt/dotnet@9/libexec
          export PATH=$DOTNET_ROOT:$PATH
          dotnet --info
      - name: Install MAUI workloads
        script: |
          dotnet workload install maui-ios
      - name: Restore NuGet packages
        script: |
          dotnet restore YourList.csproj
      - name: Build unsigned IPA
        script: |
          dotnet publish YourList.csproj \
            -f net9.0-ios \
            -c Release \
            -o ./output/ios \
            /p:BuildIpa=true \
            /p:EnableCodeSigning=false \
            /p:RuntimeIdentifier=ios-arm64
    artifacts:
      - output/ios/**/*.ipa
