workflows:
  ios-unsigned:
    name: Build unsigned iOS IPA (.NET MAUI)
    max_build_duration: 60
    environment:
      xcode: latest
    scripts:
      - name: Install .NET 8 SDK via Homebrew
        script: |
          brew update
          brew install --cask dotnet-sdk@8
          export DOTNET_ROOT=/usr/local/share/dotnet
          export PATH=$DOTNET_ROOT:$PATH
          dotnet --info
      - name: Install MAUI workloads
        script: |
          dotnet workload install maui maui-ios maui-maccatalyst
      - name: Restore NuGet packages
        script: |
          dotnet restore YourList.csproj
      - name: Build unsigned IPA
        script: |
          dotnet publish YourList.csproj \
            -f net8.0-ios \
            -c Release \
            -o ./output/ios \
            /p:BuildIpa=true \
            /p:EnableCodeSigning=false \
            /p:RuntimeIdentifier=ios-arm64
    artifacts:
      - output/ios/**/*.ipa
